project_id = "wjkbtagwgjniilmgwutb"

[functions.samsara-locations]
verify_jwt = true

[functions.samsara-debug]
verify_jwt = true

[functions.samsara-webhook]
verify_jwt = false

[functions.generate-load-confirmation]
verify_jwt = true
