project_id = "local"

[functions.samsara-locations]
verify_jwt = true

[functions.samsara-debug]
verify_jwt = true

[functions.generate-load-confirmation]
verify_jwt = true

[functions.send-load-confirmation-email]
verify_jwt = true

[functions.calculate-route]
verify_jwt = false

[functions.recalculate-load-miles]
verify_jwt = false

[functions.update-user-role]
verify_jwt = true

[functions.logout-all-users]
verify_jwt = true

[functions.check-delivery-etas]
verify_jwt = true
