import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { NewDriverExpense, DriverExpense, calculateExpenseStatus, ExpenseType } from "@/hooks/useDriverExpenses";
import { useAuthContext } from "@/contexts/AuthContext";

// Extract last segment of a name (e.g., "Aleksandar Ilic-Morgan" -> "Morgan")
function getLastNameSegment(fullName: string | null | undefined): string {
  if (!fullName) return "";
  // Split by spaces, get last part, then handle hyphenated names
  const parts = fullName.trim().split(/\s+/);
  const lastPart = parts[parts.length - 1] || "";
  // If hyphenated, get the last segment after hyphen
  const hyphenParts = lastPart.split("-");
  return hyphenParts[hyphenParts.length - 1] || lastPart;
}

interface AddDriverExpenseDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  driverId: string;
  driverName: string;
  truckNumber?: string;
  trailerNumber?: string;
  onSubmit: (expense: NewDriverExpense) => void;
  isSubmitting?: boolean;
  initialData?: DriverExpense | null;
}

export function AddDriverExpenseDialog({
  open,
  onOpenChange,
  driverId,
  driverName,
  truckNumber,
  trailerNumber,
  onSubmit,
  isSubmitting,
  initialData
}: AddDriverExpenseDialogProps) {
  const { profile } = useAuthContext();
  
  // Auto-generate name from current user's profile
  const autoGeneratedName = getLastNameSegment(profile?.full_name);

  const getInitialFormData = () => ({
    explanation: initialData?.explanation || "",
    expense_date: initialData?.expense_date || "",
    amount: initialData?.amount?.toString() || "",
    paid_date: initialData?.paid_date || "",
    paid_amount: initialData?.paid_amount?.toString() || "",
    notice_1: initialData?.notice_1 || "",
    notice_2: initialData?.notice_2 || "",
    truck_number: initialData?.truck_number || truckNumber || "",
    trailer_number: initialData?.trailer_number || trailerNumber || "",
    expense_type: initialData?.expense_type || "expense" as ExpenseType,
  });

  const [formData, setFormData] = useState(getInitialFormData);

  // Reset form when dialog opens or initialData changes
  useEffect(() => {
    if (open) {
      setFormData(getInitialFormData());
    }
  }, [open, initialData]);

  const isEditing = !!initialData;
  
  // Calculate auto-status for display
  // Company expenses are always shown as "Company Expense"
  const isCompanyExpense = formData.expense_type === 'company_expense';
  const calculatedStatus = isCompanyExpense 
    ? 'company_expense' 
    : calculateExpenseStatus(
        parseFloat(formData.amount) || 0,
        formData.paid_amount ? parseFloat(formData.paid_amount) : null
      );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // For new expenses, use auto-generated name; for edits, keep existing name
    const nameToUse = initialData?.name || autoGeneratedName;
    
    onSubmit({
      driver_id: driverId,
      name: nameToUse,
      explanation: formData.explanation,
      expense_date: formData.expense_date || null,
      amount: parseFloat(formData.amount) || 0,
      paid_date: formData.paid_date || null,
      paid_amount: formData.paid_amount ? parseFloat(formData.paid_amount) : null,
      notice_1: formData.notice_1 || null,
      notice_2: formData.notice_2 || null,
      truck_number: formData.truck_number || null,
      trailer_number: formData.trailer_number || null,
      is_fixed: initialData?.is_fixed || false,
      expense_type: formData.expense_type,
    });

    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>{isEditing ? "Edit Expense" : "Add Driver Expense"}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="truck_number">Truck</Label>
              <Input
                id="truck_number"
                value={formData.truck_number}
                onChange={(e) => setFormData({ ...formData, truck_number: e.target.value })}
                placeholder="Truck number"
              />
            </div>
            <div>
              <Label htmlFor="trailer_number">Trailer</Label>
              <Input
                id="trailer_number"
                value={formData.trailer_number}
                onChange={(e) => setFormData({ ...formData, trailer_number: e.target.value })}
                placeholder="Trailer number"
              />
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4">
            <div>
              <Label htmlFor="explanation">Explanation</Label>
              <Input
                id="explanation"
                value={formData.explanation}
                onChange={(e) => setFormData({ ...formData, explanation: e.target.value })}
                placeholder="Expense explanation"
                required
              />
            </div>
            <div>
              <Label htmlFor="expense_type">Type</Label>
              <Select
                value={formData.expense_type}
                onValueChange={(value: ExpenseType) => setFormData({ ...formData, expense_type: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="expense">Expense</SelectItem>
                  <SelectItem value="yearly">Yearly</SelectItem>
                  <SelectItem value="credit">Credit</SelectItem>
                  <SelectItem value="company_expense">Company Expense</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Added By</Label>
              <div className="h-10 flex items-center px-3 border rounded-md bg-muted text-muted-foreground text-sm">
                {initialData?.name || autoGeneratedName || "—"}
              </div>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4">
            <div>
              <Label htmlFor="expense_date">Date</Label>
              <Input
                id="expense_date"
                type="date"
                value={formData.expense_date}
                onChange={(e) => setFormData({ ...formData, expense_date: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="amount">Amount ($)</Label>
              <Input
                id="amount"
                type="number"
                step="0.01"
                value={formData.amount}
                onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                placeholder="0.00"
                required
              />
            </div>
            <div>
              <Label>Status (Auto)</Label>
              <div className="h-10 flex items-center">
                <Badge 
                  variant={
                    calculatedStatus === "paid" ? "default" : 
                    calculatedStatus === "partial" ? "secondary" : 
                    calculatedStatus === "company_expense" ? "default" :
                    "outline"
                  }
                  className={
                    calculatedStatus === "paid" ? "bg-green-500" : 
                    calculatedStatus === "partial" ? "bg-yellow-500 text-black" : 
                    calculatedStatus === "company_expense" ? "bg-purple-500" :
                    ""
                  }
                >
                  {calculatedStatus === 'company_expense' 
                    ? 'Company Expense' 
                    : calculatedStatus.charAt(0).toUpperCase() + calculatedStatus.slice(1)}
                </Badge>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="paid_date">Paid Date</Label>
              <Input
                id="paid_date"
                type="date"
                value={formData.paid_date}
                onChange={(e) => setFormData({ ...formData, paid_date: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="paid_amount">Paid Amount ($)</Label>
              <Input
                id="paid_amount"
                type="number"
                step="0.01"
                value={formData.paid_amount}
                onChange={(e) => setFormData({ ...formData, paid_amount: e.target.value })}
                placeholder="0.00"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="notice_1">Notice 1</Label>
              <Input
                id="notice_1"
                value={formData.notice_1}
                onChange={(e) => setFormData({ ...formData, notice_1: e.target.value })}
                placeholder="Notice 1"
              />
            </div>
            <div>
              <Label htmlFor="notice_2">Notice 2</Label>
              <Input
                id="notice_2"
                value={formData.notice_2}
                onChange={(e) => setFormData({ ...formData, notice_2: e.target.value })}
                placeholder="Notice 2"
              />
            </div>
          </div>

          <div className="flex justify-end gap-2 pt-4">
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? (isEditing ? "Saving..." : "Adding...") : (isEditing ? "Save Changes" : "Add Expense")}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
