// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-drivers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_drivers_default = defineTool({
  name: "list_drivers",
  title: "List drivers",
  description: "List drivers visible to the signed-in user. Optionally filter by active status or a name substring.",
  inputSchema: {
    active_only: z.boolean().optional().describe("If true, only return drivers with status = 'active'."),
    name_contains: z.string().optional().describe("Case-insensitive substring match on driver full name."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only, name_contains, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("drivers").select("id, full_name, phone, status, truck_number, trailer_number, company_id, hire_date").order("full_name", { ascending: true }).limit(limit ?? 50);
    if (active_only) query = query.eq("status", "active");
    if (name_contains) query = query.ilike("full_name", `%${name_contains}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { drivers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trucks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trucks_default = defineTool2({
  name: "list_trucks",
  title: "List trucks",
  description: "List trucks visible to the signed-in user. Optionally filter by truck number substring or company.",
  inputSchema: {
    truck_number_contains: z2.string().optional().describe("Substring match on truck_number."),
    company_id: z2.string().uuid().optional().describe("Filter by owning company UUID."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ truck_number_contains, company_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("trucks").select("id, truck_number, vin, plate, company_id, status").order("truck_number", { ascending: true }).limit(limit ?? 50);
    if (truck_number_contains) query = query.ilike("truck_number", `%${truck_number_contains}%`);
    if (company_id) query = query.eq("company_id", company_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { trucks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_orders_default = defineTool3({
  name: "list_recent_orders",
  title: "List recent orders",
  description: "List the most recently created orders/loads visible to the signed-in user. Optionally filter by load number substring, status, or canceled flag.",
  inputSchema: {
    load_number_contains: z3.string().optional().describe("Substring match on load_number or internal_load_number."),
    status: z3.string().optional().describe("Filter by exact status value."),
    include_canceled: z3.boolean().optional().describe("If false (default), excludes canceled orders."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ load_number_contains, status, include_canceled, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("orders").select("id, load_number, internal_load_number, status, canceled, pickup_datetime, delivery_datetime, freight_amount, driver_price, dispatcher_name, deleted_truck_number, broker_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    if (!include_canceled) query = query.eq("canceled", false);
    if (load_number_contains) {
      query = query.or(
        `load_number.ilike.%${load_number_contains}%,internal_load_number.ilike.%${load_number_contains}%`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wjkbtagwgjniilmgwutb";
var mcp_default = defineMcp({
  name: "beverly-tms-mcp",
  title: "Beverly TMS",
  version: "0.1.0",
  instructions: "Read-only access to Beverly TMS trucking dispatch data for the signed-in user. Use `list_drivers` to find drivers, `list_trucks` to find trucks, and `list_recent_orders` to inspect recent loads. All results are scoped by the user's role and RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_drivers_default, list_trucks_default, list_recent_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
