INSERT INTO public.hr_reports (driver_name, truck_number, problem_type, problem_other, reason, updates, is_pinned, is_resolved, resolved_at, archived, archived_at, reviewed, reviewed_at, reviewed_by_name, created_by_name, created_at)
VALUES
('Damon Fernandez','6276','dispatcher',NULL,'Driver says he is not getting enough miles, wants to talk to a manager.','Called him, explained the plan for next week.',true,false,NULL,false,NULL,false,NULL,NULL,'Djordje Ljubicic',now() - interval '2 hours'),
('Liam Berkes','5873','maintenance',NULL,'APU not working, cabin too hot at night.','Scheduled for in-house repair Friday.',false,false,NULL,false,NULL,false,NULL,NULL,'Djordje Ljubicic',now() - interval '5 hours'),
('Danny Thacker','0814','accounting',NULL,'Missing reimbursement for scale ticket from last week.','Sent to accounting for review.',false,false,NULL,false,NULL,false,NULL,NULL,'Djordje Ljubicic',now() - interval '1 day'),
('Mahamat Dogo Abdoulaye','6459','recruiting',NULL,'Says he was promised a newer truck when he was hired.','Recruiter confirming what was offered.',false,false,NULL,false,NULL,false,NULL,NULL,'Djordje Ljubicic',now() - interval '1 day 3 hours'),
('Anthony Steward','5869','other','Home time','Requesting home time every two weeks instead of three.','Discussed with his dispatcher.',false,false,NULL,false,NULL,false,NULL,NULL,'Djordje Ljubicic',now() - interval '2 days'),
('Keith Dobbins','385','dispatcher',NULL,'Complains dispatcher does not answer calls at night.','Reviewing call records.',false,false,NULL,false,NULL,false,NULL,NULL,'Djordje Ljubicic',now() - interval '2 days 6 hours'),
('Levarr Hart','3073','maintenance',NULL,'Trailer tires worn, wants a trailer swap.','Trailer swap approved at yard.',false,false,NULL,false,NULL,false,NULL,NULL,'Djordje Ljubicic',now() - interval '3 days'),
('Jhoan Lizardo','2884','other','Equipment','Asking for extra straps and load bars.','Will pick up at yard on next return.',false,false,NULL,false,NULL,false,NULL,NULL,'Djordje Ljubicic',now() - interval '3 days 4 hours'),
('Olutosin Odusote','7764','accounting',NULL,'Statement shows a deduction he does not recognize.','Explained ELD and insurance deductions, issue closed.',false,true,now() - interval '6 days',true,now() - interval '5 days',true,now() - interval '5 days','Djordje Ljubicic','Djordje Ljubicic',now() - interval '7 days'),
('Justin Redus','9493','maintenance',NULL,'Engine overheating warning on the dash.','Repaired at outside shop, back in service.',false,true,now() - interval '8 days',true,now() - interval '7 days',true,now() - interval '7 days','Djordje Ljubicic','Djordje Ljubicic',now() - interval '9 days'),
('Kennda Mack','3071','dispatcher',NULL,'Unhappy with loads assigned over the weekend.','Talked with weekend dispatcher, resolved.',false,true,now() - interval '10 days',true,now() - interval '9 days',false,NULL,NULL,'Djordje Ljubicic',now() - interval '11 days'),
('Mark Scaplen','8555','recruiting',NULL,'Referral bonus for a friend he brought in was not paid.','Bonus processed with next payroll.',false,true,now() - interval '12 days',true,now() - interval '11 days',true,now() - interval '11 days','Djordje Ljubicic','Djordje Ljubicic',now() - interval '13 days'),
('Thomas A Ludwig','3296','other','Safety','Wants to review a roadside inspection result.','Safety went over the report with him.',false,true,now() - interval '14 days',true,now() - interval '13 days',false,NULL,NULL,'Djordje Ljubicic',now() - interval '15 days'),
('Terrence Walker','6736','accounting',NULL,'Asking about escrow balance and when it is returned.','Accounting sent him the breakdown.',false,true,now() - interval '16 days',true,now() - interval '15 days',true,now() - interval '15 days','Djordje Ljubicic','Djordje Ljubicic',now() - interval '17 days'),
('Judelens Joseph','04660','maintenance',NULL,'Fridge stopped cooling, food spoiled.','New fridge installed, expense noted.',false,true,now() - interval '18 days',true,now() - interval '17 days',true,now() - interval '17 days','Djordje Ljubicic','Djordje Ljubicic',now() - interval '19 days');