UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2018, miles=639426, engine='PACCAR', has_apu_webasto=false, has_inverter=false, has_fridge=false WHERE truck_number='2695';
UPDATE trucks SET make='VOLVO M&K', model='760', transmission='Automatic', year=2024, miles=81837, engine='D13', has_apu_webasto=false, has_inverter=false, has_fridge=false WHERE truck_number='241139';
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2024, miles=245317, engine='PACCAR', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='3213';
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=70000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='5596';
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='5596') AND id IS NOT NULL;
UPDATE trucks SET make='VOLVO', model='VNL 760', transmission='Automatic', year=2023, miles=500000, engine='D13', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='0760';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='0760') AND id IS NOT NULL;
UPDATE trucks SET make='VOLVO', model='VNL 760', transmission='Automatic', year=2024, miles=460000, engine='VOLVO', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='0765';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='0765') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=90000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number IN ('O2389','02389','2389');
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number IN ('O2389','02389','2389') LIMIT 1) AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=34000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='2393';
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2393') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=155000, engine='CUMMINS', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='779';
UPDATE drivers SET weekly_payment=850, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='779') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=180000, engine='CUMMINS', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='927';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='927') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2025, miles=200000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='926';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='926') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2023, miles=95000, engine='PACCAR', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='1305';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='1305') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=120000, engine='CUMMINS', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='2103';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2103') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=120000, engine='CUMMINS', has_apu_webasto=false, has_inverter=false, has_fridge=true WHERE truck_number='2115';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2115') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=150000, engine='CUMMINS', has_apu_webasto=false, has_inverter=false, has_fridge=true WHERE truck_number='2119';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2119') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=120000, engine='CUMMINS', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='2122';
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2122') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=120000, engine='CUMMINS', has_apu_webasto=false, has_inverter=false, has_fridge=true WHERE truck_number='2154';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2154') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=80000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='2415';
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2415') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2026, miles=35000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='3140';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='3140') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=185000, engine='CUMMINS', has_apu_webasto=false, has_inverter=false, has_fridge=true WHERE truck_number='3293';
UPDATE drivers SET weekly_payment=850, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='3293') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2025, miles=225000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='3868';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='3868') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2025, miles=180000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='4628';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='4628') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2025, miles=270000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='4656';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='4656') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2025, miles=265000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=false WHERE truck_number='4664';
UPDATE drivers SET weekly_payment=750, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='4664') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=135000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='5601';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='5601') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=100000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='5613';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='5613') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2023, miles=450000, engine='PACCAR', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='5646';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='5646') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2025, miles=245000, engine='PACCAR', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='5941';
UPDATE drivers SET weekly_payment=750, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='5941') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=135000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='7346';
UPDATE drivers SET weekly_payment=850, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='7346') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2023, miles=495000, engine='CUMMINS', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='7348';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='7348') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2024, miles=240000, engine='CUMMINS', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='8497';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='8497') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=120000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='8514';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='8514') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=100000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='8578';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='8578') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=90000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='8581';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='8581') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2024, miles=315000, engine='PACCAR', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='8762';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='8762') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2025, miles=200000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='9494';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='9494') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER RYDER', model='CASCADIA', transmission='Automatic', year=2024, miles=400000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='713962';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='713962') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER RYDER', model='CASCADIA', transmission='Automatic', year=2026, miles=110000, engine='DD15', has_apu_webasto=true, has_inverter=false, has_fridge=true WHERE truck_number='255358';
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='255358') AND id IS NOT NULL;