-- Backfill truck specs (make/model/transmission/year/miles/engine and APU/Inverter/Fridge flags)
-- and driver weekly_payment / weeks_count from Copy of Truck Sales spreadsheet
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2025, miles=160631, engine='CUMMINS', has_apu_webasto=false, has_inverter=false, has_fridge=true WHERE truck_number='9552';
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=85000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='2396';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2396') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2024, miles=465000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='0984';
UPDATE drivers SET weekly_payment=600, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='0984') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2026, miles=120000, engine='CUMMINS', has_apu_webasto=false, has_inverter=false, has_fridge=true WHERE truck_number='2106';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2106') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=75000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='2309';
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2309') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=100000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='2370';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2370') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=95000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='2391';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2391') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2026, miles=145000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='2934';
UPDATE drivers SET weekly_payment=850, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='2934') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2025, miles=255000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='3870';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='3870') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2024, miles=400000, engine='DD16', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='3926';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='3926') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2027, miles=20000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='4650';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='4650') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2027, miles=15000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='4651';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='4651') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2025, miles=240000, engine='PACCAR', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='4677';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='4677') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=35000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='4696';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='4696') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2025, miles=250000, engine='PACCAR', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='4709';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='4709') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=120000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='5597';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='5597') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=90000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='5600';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='5600') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=40000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='5610';
UPDATE drivers SET weekly_payment=900, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='5610') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=160000, engine='DD15', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='7339';
UPDATE drivers SET weekly_payment=850, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='7339') AND id IS NOT NULL;
UPDATE trucks SET make='VOLVO', model='VLN 660', transmission='Automatic', year=2026, miles=150000, engine='VOLVO D13', has_apu_webasto=false, has_inverter=false, has_fridge=false WHERE truck_number='7327';
UPDATE drivers SET weekly_payment=850, weeks_count=182 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='7327') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=100000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='8547';
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='8547') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2024, miles=320000, engine='PACCAR', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='8760';
UPDATE drivers SET weekly_payment=600, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='8760') AND id IS NOT NULL;
UPDATE trucks SET make='KENWORTH', model='T680', transmission='Automatic', year=2024, miles=340000, engine='PACCAR', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='8761';
UPDATE drivers SET weekly_payment=600, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='8761') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2025, miles=215000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='9496';
UPDATE drivers SET weekly_payment=800, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='9496') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2026, miles=60000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='9874';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='9874') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER', model='CASCADIA', transmission='Automatic', year=2024, miles=385000, engine='DD13', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='9677';
UPDATE drivers SET weekly_payment=600, weeks_count=130 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='9677') AND id IS NOT NULL;
UPDATE trucks SET make='VOLVO M&K', model='VNL 760', transmission='Automatic', year=2024, miles=280000, engine='D13', has_apu_webasto=false, has_inverter=true, has_fridge=true WHERE truck_number='241137';
UPDATE drivers SET weekly_payment=750, weeks_count=156 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='241137') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER RYDER', model='CASCADIA', transmission='Automatic', year=2026, miles=95000, engine='DD15', has_apu_webasto=true, has_inverter=false, has_fridge=true WHERE truck_number='255361';
UPDATE drivers SET weekly_payment=900, weeks_count=191 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='255361') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER RYDER', model='CASCADIA', transmission='Automatic', year=2026, miles=20000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='203191';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='203191') AND id IS NOT NULL;
UPDATE trucks SET make='FREIGHTLINER RYDER', model='CASCADIA', transmission='Automatic', year=2026, miles=25000, engine='DD15', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='203192';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='203192') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2027, miles=0, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='34649';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='34649') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2027, miles=25000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='34664';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='34664') AND id IS NOT NULL;
UPDATE trucks SET make='PETERBILT', model='579', transmission='Automatic', year=2027, miles=20000, engine='CUMMINS', has_apu_webasto=true, has_inverter=true, has_fridge=true WHERE truck_number='34663';
UPDATE drivers SET weekly_payment=900, weeks_count=208 WHERE id = (SELECT driver1_id FROM trucks WHERE truck_number='34663') AND id IS NOT NULL;